agents:
  queue: <%- prodBuildkiteQueueName %>

configs:
  plugins:
    - &aws-sm
      seek-oss/aws-sm#v2.3.2:
        env:
          NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token

    - &docker-ecr-cache
      seek-oss/docker-ecr-cache#v2.2.0: &docker-ecr-cache-defaults
        cache-on:
          - .npmrc
          - package.json#.packageManager
          - pnpm-lock.yaml
        dockerfile: Dockerfile.dev-deps
        secrets: id=npm,src=tmp/.npmrc

    - &private-npm
      seek-oss/private-npm#v1.2.0:
        env: NPM_READ_TOKEN
        output-path: tmp/

  base-steps:
    - &deploy
      concurrency: 1
      retry:
        manual:
          # Only use this if you need to roll back a deployment ASAP.
          # Always follow up with a proper revert or fix in Git history.
          permit_on_passed: true

steps:
  - label: 🧖‍♀️ Warm Prod
    command: ':'
    key: warm-prod
    plugins:
      - *aws-sm
      - *private-npm
      - seek-oss/docker-ecr-cache#v2.2.0:
          <<: *docker-ecr-cache-defaults
          skip-pull-from-cache: true

  - label: 🧪 Test & Lint
    commands:
      - echo '--- pnpm install --offline'
      - pnpm install --offline
      - echo '+++ pnpm test:ci'
      - pnpm test:ci
      - echo '--- pnpm lint'
      - pnpm lint
    depends_on: warm-prod
    env:
      GET_GITHUB_TOKEN: please
    plugins:
      - *aws-sm
      - *private-npm
      - *docker-ecr-cache
      - docker-compose#v5.3.0:
          run: app
          environment:
            - GITHUB_API_TOKEN
          propagate-environment: true
    timeout_in_minutes: 10

  - label: 📦 Build & Package
    depends_on: warm-prod
    plugins:
      - *aws-sm
      - *private-npm
      - *docker-ecr-cache
      - seek-jobs/gantry#v3.0.0:
          command: build
          file: gantry.build.yml
          region: <%- region %>
          values: .gantry/common.yml

  - wait
  - block: 🙋🏻‍♀️ Deploy Dev
    branches: '!${BUILDKITE_PIPELINE_DEFAULT_BRANCH}'

  - <<: *deploy
    agents:
      queue: <%- devBuildkiteQueueName %>
    label: 🤞 Deploy Dev
    concurrency_group: <%- teamName %>/deploy/gantry/<%- devGantryEnvironmentName %>
    key: deploy-dev
    plugins:
      - seek-jobs/gantry#v3.0.0:
          command: apply
          environment: <%- devGantryEnvironmentName %>
          file: gantry.apply.yml
          region: <%- region %>
          values:
            - .gantry/common.yml
            - .gantry/dev.yml

  - <<: *deploy
    label: 🚀 Deploy Prod
    branches: ${BUILDKITE_PIPELINE_DEFAULT_BRANCH}
    concurrency_group: <%- teamName %>/deploy/gantry/<%- prodGantryEnvironmentName %>
    depends_on: deploy-dev
    plugins:
      - seek-jobs/gantry#v3.0.0:
          command: apply
          environment: <%- prodGantryEnvironmentName %>
          file: gantry.apply.yml
          region: <%- region %>
          values:
            - .gantry/common.yml
            - .gantry/prod.yml
