configs:
  - &aws-sm
    seek-oss/aws-sm#v2.0.0:
      env:
        NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token

  - &deploy
    concurrency: 1
    retry:
      manual:
        # Only use this if you need to roll back a deployment ASAP.
        # Always follow up with a proper revert or fix in Git history.
        permit_on_passed: true

  - &dev
    agents:
      queue: <%- devBuildkiteQueueName %>

  - &prod
    agents:
      queue: <%- prodBuildkiteQueueName %>

steps:
  - <<: *prod
    label: 🧪 Test & Lint
    commands:
      - echo '+++ yarn test'
      - yarn test
      - echo '+++ yarn lint'
      - yarn lint
    plugins:
      - *aws-sm
      - ecr#v2.2.0:
          login: true
      - docker-compose#v3.7.0:
          run: app

  - <<: *prod
    label: 📦 Build & Package
    plugins:
      - *aws-sm
      - seek-jobs/gantry#v1.2.11:
          command: build
          file: gantry.build.yml
          values: .gantry/common.yml

  - wait
  - block: 🙋🏻‍♀️ Deploy Dev
    branches: '!master'

  - <<: *dev
    <<: *deploy
    label: 🤞 Deploy Dev
    concurrency_group: <%- teamName %>/deploy/gantry/<%- devGantryEnvironmentName %>
    plugins:
      - seek-jobs/gantry#v1.2.11:
          command: apply
          environment: <%- devGantryEnvironmentName %>
          file: gantry.apply.yml
          values:
            - .gantry/common.yml
            - .gantry/dev.yml

  - wait

  - <<: *prod
    <<: *deploy
    label: 🚀 Deploy Prod
    branches: master
    concurrency_group: <%- teamName %>/deploy/gantry/<%- prodGantryEnvironmentName %>
    plugins:
      - seek-jobs/gantry#v1.2.11:
          command: apply
          environment: <%- prodGantryEnvironmentName %>
          file: gantry.apply.yml
          values:
            - .gantry/common.yml
            - .gantry/prod.yml
