configs:
  environments:
    - &dev
      agents:
        queue: <%- devBuildkiteQueueName %>

    - &prod
      agents:
        queue: <%- prodBuildkiteQueueName %>

  plugins:
    - &aws-sm
      seek-oss/aws-sm#v2.3.1:
        env:
          NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token

    - &docker
      docker#v3.8.0:
        volumes:
          - /workdir/lib
          - /workdir/node_modules

    - &docker-ecr-cache
      seek-oss/docker-ecr-cache#v1.11.0:
        build-args:
          - NPM_READ_TOKEN
        cache-on:
          - package.json
          - yarn.lock

  base-steps:
    - &deploy
      concurrency: 1
      plugins:
        - *aws-sm
        - *docker-ecr-cache
        - *docker
      retry:
        manual:
          # Only use this if you need to roll back a deployment ASAP.
          # Always follow up with a proper revert or fix in Git history.
          permit_on_passed: true

steps:
  - <<: *dev
    label: 🧪 Test & Lint
    commands:
      - echo '+++ yarn test:ci'
      - yarn test
      - echo '--- yarn lint'
      - yarn lint
    plugins:
      - *aws-sm
      - *docker-ecr-cache
      - *docker

  - wait
  - block: 🙋🏻‍♀️ Deploy Dev
    branches: '!master'

  - <<: *dev
    <<: *deploy
    label: 🤞 Deploy Dev
    commands:
      - echo '--- yarn build'
      - yarn build
      - echo '+++ yarn deploy:dev'
      - yarn deploy:dev
    concurrency_group: '<%- repoName %>/deploy/dev'
    key: deploy-dev

  - <<: *prod
    <<: *deploy
    label: 🚀 Deploy Prod
    branches: master
    commands:
      - echo '--- yarn build'
      - yarn build
      - echo '+++ yarn deploy:prod'
      - yarn deploy:prod
    concurrency_group: '<%- repoName %>/deploy/prod'
    depends_on: deploy-dev
