dev-agent: &dev-agent
  agents:
    queue: <%- devBuildkiteQueueName %>

prod-agent: &prod-agent
  agents:
    queue: <%- prodBuildkiteQueueName %>

plugins: &plugins #alias for shared plugins
  seek-oss/aws-sm#v2.3.1:
    env:
      NPM_READ_TOKEN: 'arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token'
  docker#v3.8.0:
    volumes:
      - /workdir/node_modules
      - /workdir/lib
    environment:
      - NPM_READ_TOKEN
  seek-oss/docker-ecr-cache#v1.9.0:
    build-args:
      - NPM_READ_TOKEN
    cache-on:
      - package.json
      - yarn.lock

steps:
  - label: ':yarn: :eslint: Lint  and :jest: unit test'
    <<: *dev-agent
    plugins:
      <<: *plugins
    key: test
    command:
      - echo "--- Running yarn lint"
      - yarn lint
      - echo "--- Running yarn test :jest:"
      - yarn test

  - label: 'CDK Deploy Staging  :shipit:'
    <<: *dev-agent
    plugins:
      <<: *plugins
    depends_on:
      - test
    command:
      - echo "--- Running CDK deploy to staging"
      - yarn deploy:dev
    concurrency: 1
    concurrency_group: '<%- repoName %>/deploy/dev'

  - label: 'CDK Deploy Production  :shipit:'
    branches: 'master'
    <<: *prod-agent
    plugins:
      <<: *plugins
    depends_on:
      - test
    command:
      - echo "--- Running CDK deploy to production"
      - yarn deploy:prod
    concurrency: 1
    concurrency_group: '<%- repoName %>/deploy/prod'
