agents:
  queue: <%- prodBuildkiteQueueName %>

configs:
  plugins:
    - &docker-ecr-cache
      seek-oss/docker-ecr-cache#v2.2.1: &docker-ecr-cache-defaults
        cache-on:
          - .npmrc
          - package.json#.packageManager
          - pnpm-lock.yaml
        secrets:
          - id=npm,src=/var/lib/buildkite-agent/.npmrc
          - NPM_TOKEN

  base-steps:
    - &deploy
      commands:
        - echo '--- pnpm install --offline'
        - pnpm install --offline
        - echo '+++ pnpm run deploy'
        - pnpm run deploy
      concurrency: 1
      plugins:
        - *docker-ecr-cache
        - docker-compose#v5.7.0:
            dependencies: false
            run: app
            environment:
              - GITHUB_API_TOKEN
            propagate-environment: true
      retry:
        manual:
          # Only use this if you need to roll back a deployment ASAP.
          # Always follow up with a proper revert or fix in Git history.
          permit_on_passed: true

env:
  VERSION: ${BUILDKITE_COMMIT:0:7}.${BUILDKITE_BUILD_NUMBER}

steps:
  - label: 🧪 Test, Lint & Build
    commands:
      - echo '--- pnpm install --offline'
      - pnpm install --offline
      - echo '+++ pnpm test:ci'
      - pnpm test
      - echo '--- pnpm lint'
      - pnpm lint
    env:
      GET_NPM_TOKEN: please
      GET_GITHUB_TOKEN: please
    plugins:
      - *docker-ecr-cache
      - docker-compose#v5.7.0:
          run: app
          environment:
            - GITHUB_API_TOKEN
          propagate-environment: true
    timeout_in_minutes: 10

  - agents:
      queue: <%- devBuildkiteQueueName %>
    branches: '!renovate-*'
    env:
      GET_NPM_TOKEN: please
    label: 🧖‍♀️ Warm Dev
    command: ':'
    plugins:
      - seek-oss/docker-ecr-cache#v2.2.1:
          <<: *docker-ecr-cache-defaults
          skip-pull-from-cache: true

  - wait

  - block: 🙋🏻‍♀️ Deploy Dev
    branches: '!${BUILDKITE_PIPELINE_DEFAULT_BRANCH}'

  - <<: *deploy
    agents:
      queue: <%- devBuildkiteQueueName %>
    env:
      GET_NPM_TOKEN: please
      ENVIRONMENT: dev
    label: 🤞 Deploy Dev
    concurrency_group: '<%- repoName %>/deploy/dev'
    key: deploy-dev

  - <<: *deploy
    env:
      GET_NPM_TOKEN: please
      ENVIRONMENT: prod
    label: 🚀 Deploy Prod
    branches: ${BUILDKITE_PIPELINE_DEFAULT_BRANCH}
    concurrency_group: '<%- repoName %>/deploy/prod'
    depends_on: deploy-dev
