$schema: https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
agents:
  queue: artefacts:npm2

steps:
  - command: aws s3 cp s3://seek-npm-package-buildkite-pipeline/pipeline-latest.sh - | bash | buildkite-agent pipeline upload
