# managed by skuba
packageManagerStrictVersion: true
publicHoistPattern:
  - '@types*'
  - '*eslint*'
  - '*prettier*'
  - esbuild
  - jest
  - tsconfig-seek
  # end managed by skuba
  - 'remark-lint-*'
packages:
  # https://github.com/changesets/changesets/issues/1133#issuecomment-1594844204
  - .
  - packages/*
  - template/*
nodeOptions: '--experimental-vm-modules --no-warnings=ExperimentalWarning'
