packages:
  - .
  - packages/*
  - template/*

configDependencies:
  pnpm-plugin-sku: 0.0.3+sha512-XPcqT+jnn4oGgkUCMLSmlj3R367WTD6O8TlIufxAej7TfE28h4IOVWaJdqVWIq2QRqGoJxjCCXUhlT5Y0vIHaQ==

overrides:
  skuba: workspace:*
  skuba-dive: workspace:*

publicHoistPattern:
  - remark-lint-*
