packages:
  # https://github.com/changesets/changesets/issues/1133#issuecomment-1594844204
  - .
  - packages/*
  - template/*

overrides:
  skuba: workspace:*
  skuba-dive: workspace:*

patchedDependencies:
  '@ast-grep/lang-json@0.0.6': patches/@ast-grep__lang-json@0.0.6.patch

publicHoistPattern:
  - remark-lint-*

trustPolicyExclude:
  - undici-types@6.21.0 # remark-cli has a nested dependency on @types/node@22.19.13
