# managed by skuba
ignorePatchFailures: false
minimumReleaseAge: 4320 # 3 days
strictDepBuilds: true
onlyBuiltDependencies:
  - '@ast-grep/lang-json'
  - '@datadog/native-appsec'
  - '@datadog/native-iast-taint-tracking'
  - '@datadog/native-metrics'
  - '@datadog/pprof'
  - dd-trace
  - esbuild
  - protobufjs
  - unix-dgram
  - unrs-resolver
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'pino@9.14.0'
  - 'semver@5.7.2 || 6.3.1'
  - 'undici-types@6.21.0' # https://github.com/nodejs/undici/issues/4666
minimumReleaseAgeExclude:
  - '@seek/*'
  - '@skuba-lib/*'
  - eslint-config-seek
  - eslint-config-skuba
  - eslint-plugin-skuba
  - skuba
  - skuba-dive
  - tsconfig-seek
packageManagerStrictVersion: true
publicHoistPattern:
  - '@eslint/*'
  - '@types*'
  - eslint
  - eslint-config-skuba
  - prettier
  - esbuild
  - jest
  - tsconfig-seek
  - typescript
  # end managed by skuba
  - 'remark-lint-*'

packages:
  # https://github.com/changesets/changesets/issues/1133#issuecomment-1594844204
  - .
  - packages/*
  - template/*

overrides:
  'skuba': 'workspace:*'
  'skuba-dive': 'workspace:*'
