# managed by skuba
ignorePatchFailures: false
# minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@seek/*'
  - '@skuba-lib/*'
  - eslint-config-seek
  - eslint-config-skuba
  - eslint-plugin-skuba
  - skuba
  - tsconfig-seek
packageManagerStrictVersion: true
publicHoistPattern:
  - '@types*'
  - '@vitest/*'
  - eslint
  - eslint-config-skuba
  - prettier
  - esbuild
  - tsconfig-seek
  - typescript
  - vitest
  # end managed by skuba
  - 'remark-lint-*'

packages:
  # https://github.com/changesets/changesets/issues/1133#issuecomment-1594844204
  - .
  - packages/*
  - template/*

overrides:
  'skuba': 'workspace:*'
