# managed by skuba
packageManagerStrictVersion: true
publicHoistPattern:
  - '@types*'
  - eslint
  - eslint-config-skuba
  - prettier
  - esbuild
  - jest
  - tsconfig-seek
  - typescript
  # end managed by skuba
  - 'remark-lint-*'
packages:
  # https://github.com/changesets/changesets/issues/1133#issuecomment-1594844204
  - .
  - packages/*
  - template/*
