agents:
  queue: <%- prodBuildkiteQueueName %>

configs:
  plugins:
    - &docker-ecr-cache
      seek-oss/docker-ecr-cache#v2.2.1: &docker-ecr-cache-defaults
        cache-on:
          - package.json#.packageManager
          - pnpm-lock.yaml
          - pnpm-workspace.yaml
        dockerfile: Dockerfile.dev-deps
        secrets:
          - id=npm,src=/var/lib/buildkite-agent/.npmrc
          - NPM_TOKEN

  base-steps:
    - &deploy
      concurrency: 1
      retry:
        manual:
          # Only use this if you need to roll back a deployment ASAP.
          # Always follow up with a proper revert or fix in Git history.
          permit_on_passed: true

steps:
  - label: 🧖‍♀️ Warm Prod
    command: ':'
    env:
      GET_NPM_TOKEN: please
    key: warm-prod
    plugins:
      - seek-oss/docker-ecr-cache#v2.2.1:
          <<: *docker-ecr-cache-defaults
          skip-pull-from-cache: true

  - label: 🧪 Test & Lint
    commands:
      - echo '--- pnpm install --offline'
      - pnpm install --offline
      - echo '+++ pnpm test:ci'
      - pnpm test:ci
      - echo '--- pnpm lint'
      - pnpm lint
    depends_on: warm-prod
    env:
      GET_GITHUB_TOKEN: please
      GET_NPM_TOKEN: please
    plugins:
      - *docker-ecr-cache
      - docker-compose#v5.7.0:
          run: app
          environment:
            - GITHUB_API_TOKEN
          propagate-environment: true
    timeout_in_minutes: 10

  - label: 📦 Build & Package
    depends_on: warm-prod
    env:
      GET_NPM_TOKEN: please
    plugins:
      - *docker-ecr-cache
      - seek-jobs/gantry#v4.0.0:
          command: build
          file: gantry.build.yml
          region: <%- region %>
          values: .gantry/common.yml

  - wait
  - block: 🙋🏻‍♀️ Deploy Dev
    branches: '!${BUILDKITE_PIPELINE_DEFAULT_BRANCH}'

  - <<: *deploy
    agents:
      queue: <%- devBuildkiteQueueName %>
    label: 🤞 Deploy Dev
    concurrency_group: <%- teamName %>/deploy/gantry/<%- devGantryEnvironmentName %>
    key: deploy-dev
    plugins:
      - seek-jobs/gantry#v4.0.0:
          command: apply
          environment: <%- devGantryEnvironmentName %>
          file: gantry.apply.yml
          region: <%- region %>
          values:
            - .gantry/common.yml
            - .gantry/dev.yml

  - <<: *deploy
    label: 🚀 Deploy Prod
    branches: ${BUILDKITE_PIPELINE_DEFAULT_BRANCH}
    concurrency_group: <%- teamName %>/deploy/gantry/<%- prodGantryEnvironmentName %>
    depends_on: deploy-dev
    plugins:
      - seek-jobs/gantry#v4.0.0:
          command: apply
          environment: <%- prodGantryEnvironmentName %>
          file: gantry.apply.yml
          region: <%- region %>
          values:
            - .gantry/common.yml
            - .gantry/prod.yml
