configs:
  - &aws-sm
    seek-oss/aws-sm#v2.0.0:
      env:
        NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token

  - &prod
    agents:
      queue: <%- prodBuildkiteQueueName %>

steps:
  - <<: *prod
    label: 🧪 Test & Lint
    commands:
      - echo '+++ yarn test'
      - yarn test
      - echo '+++ yarn lint'
      - yarn lint
    plugins:
      - *aws-sm
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.3.0:
          run: app
