configs:
  - &aws-sm
    seek-oss/aws-sm#v2.0.0:
      env:
        NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token

  - &docker-ecr-cache
    seek-oss/docker-ecr-cache#v1.5.0:
      build-args:
        - NPM_READ_TOKEN
      cache-on:
        - package.json
        - yarn.lock
      target: dev-deps

  - &prod
    agents:
      queue: <%- prodBuildkiteQueueName %>

steps:
  - <<: *prod
    label: 🧪 Test & Lint
    commands:
      - echo '+++ yarn test'
      - yarn test
      - echo '+++ yarn lint'
      - yarn lint
    plugins:
      - *aws-sm
      - *docker-ecr-cache
      - docker-compose#v3.7.0:
          run: app
