agents:
  queue: <%- prodBuildkiteQueueName %>

configs:
  plugins:
    - &aws-sm
      seek-oss/aws-sm#v2.3.1:
        env:
          NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token

    - &docker-ecr-cache
      seek-oss/docker-ecr-cache#v2.0.0:
        cache-on:
          - package.json
          - yarn.lock
        secrets: id=npm,src=.npmrc

    - &private-npm
      seek-oss/private-npm#v1.2.0:
        env: NPM_READ_TOKEN

steps:
  - label: 🧪 Test & Lint
    commands:
      - echo '+++ yarn test:ci'
      - yarn test:ci
      - echo '--- yarn lint'
      - yarn lint
    env:
      GET_GITHUB_TOKEN: please
    plugins:
      - *aws-sm
      - *private-npm
      - *docker-ecr-cache
      - docker-compose#v4.14.0:
          run: app
    timeout_in_minutes: 10
