agents:
  queue: <%- prodBuildkiteQueueName %>

configs:
  plugins:
    - &aws-sm
      seek-oss/aws-sm#v2.3.2:
        env:
          NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token

    - &docker-ecr-cache
      seek-oss/docker-ecr-cache#v2.1.1:
        cache-on:
          - .npmrc
          - pnpm-lock.yaml
        secrets: id=npm,src=tmp/.npmrc

    - &private-npm
      seek-oss/private-npm#v1.2.0:
        env: NPM_READ_TOKEN
        output-path: tmp/

steps:
  - label: 🧪 Test & Lint
    commands:
      - echo '--- pnpm install --offline'
      - pnpm install --offline
      - echo '+++ pnpm test:ci'
      - pnpm test:ci
      - echo '--- pnpm lint'
      - pnpm lint
    env:
      GET_GITHUB_TOKEN: please
    plugins:
      - *aws-sm
      - *private-npm
      - *docker-ecr-cache
      - docker-compose#v5.2.0:
          run: app
          environment:
            - GITHUB_API_TOKEN
          propagate-environment: true
    timeout_in_minutes: 10
