env:
  VERSION: ${BUILDKITE_COMMIT:0:7}.${BUILDKITE_BUILD_NUMBER}

configs:
  environments:
    - &dev
      agents:
        queue: <%- devBuildkiteQueueName %>
      env:
        ENVIRONMENT: dev

    - &prod
      agents:
        queue: <%- prodBuildkiteQueueName %>
      env:
        ENVIRONMENT: prod

  plugins:
    - &aws-sm
      seek-oss/aws-sm#v2.3.1:
        env:
          NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token

    - &docker-ecr-cache
      seek-oss/docker-ecr-cache#v1.11.0:
        cache-on:
          - package.json
          - yarn.lock
        secrets: id=npm,src=.npmrc

    - &private-npm
      seek-oss/private-npm#v1.2.0:
        env: NPM_READ_TOKEN

  base-steps:
    - &deploy
      commands:
        - echo '+++ yarn deploy'
        - yarn deploy
      concurrency: 1
      plugins:
        - artifacts#v1.5.0:
            build: ${BUILDKITE_BUILD_ID}
            download: lib/*
        - *aws-sm
        - *private-npm
        - *docker-ecr-cache
        - docker-compose#v3.9.0:
            dependencies: false
            run: app
      retry:
        manual:
          # Only use this if you need to roll back a deployment ASAP.
          # Always follow up with a proper revert or fix in Git history.
          permit_on_passed: true

steps:
  - <<: *prod
    label: 🧪 Test, Lint & Build
    artifact_paths: lib/**/*
    commands:
      - echo '+++ yarn test:ci'
      - yarn test:ci
      - echo '--- yarn lint'
      - yarn lint
      - echo '--- yarn build'
      - yarn build
    env:
      GET_GITHUB_TOKEN: please
    plugins:
      - *aws-sm
      - *private-npm
      - *docker-ecr-cache
      - docker-compose#v3.9.0:
          run: app

  - <<: *dev
    branches: '!renovate/*'
    label: 🧖‍♀️ Warm Dev
    command: ':'
    plugins:
      - *aws-sm
      - *private-npm
      - *docker-ecr-cache

  - wait
  - block: 🙋🏻‍♀️ Deploy Dev
    branches: '!${BUILDKITE_PIPELINE_DEFAULT_BRANCH}'

  - <<: *dev
    <<: *deploy
    concurrency_group: <%- repoName %>/deploy/dev
    label: 🤞 Deploy Dev

  - wait

  - <<: *prod
    <<: *deploy
    branches: ${BUILDKITE_PIPELINE_DEFAULT_BRANCH}
    concurrency_group: <%- repoName %>/deploy/prod
    label: 🚀 Deploy Prod
