env:
  VERSION: ${BUILDKITE_COMMIT:0:7}.${BUILDKITE_BUILD_NUMBER}

configs:
  environments:
    - &dev
      agents:
        queue: <%- devBuildkiteQueueName %>
      env:
        ENVIRONMENT: dev

    - &prod
      agents:
        queue: <%- prodBuildkiteQueueName %>
      env:
        ENVIRONMENT: prod

  plugins:
    - &aws-sm
      seek-oss/aws-sm#v2.0.0:
        env:
          NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token

    - &docker-ecr-cache
      seek-oss/docker-ecr-cache#v1.5.0:
        build-args:
          - NPM_READ_TOKEN
        cache-on:
          - package.json
          - yarn.lock
        target: dev-deps

  base-steps:
    - &deploy
      concurrency: 1
      plugins:
        - *aws-sm
        - *docker-ecr-cache
        - docker-compose#v3.7.0:
            dependencies: false
            run: app
      retry:
        manual:
          # Only use this if you need to roll back a deployment ASAP.
          # Always follow up with a proper revert or fix in Git history.
          permit_on_passed: true

steps:
  - <<: *prod
    label: 🧪 Test & Lint
    commands:
      - echo '+++ yarn test:ci'
      - yarn test:ci
      - echo '--- yarn lint'
      - yarn lint
    plugins:
      - *aws-sm
      - *docker-ecr-cache
      - docker-compose#v3.7.0:
          run: app

  - wait
  - block: 🙋🏻‍♀️ Deploy Dev
    branches: '!${BUILDKITE_PIPELINE_DEFAULT_BRANCH}'

  - <<: *dev
    <<: *deploy
    command: yarn deploy
    concurrency_group: <%- repoName %>/deploy/dev
    label: 🤞 Deploy Dev

  - wait

  - <<: *prod
    <<: *deploy
    branches: ${BUILDKITE_PIPELINE_DEFAULT_BRANCH}
    command: yarn deploy
    concurrency_group: <%- repoName %>/deploy/prod
    label: 🚀 Deploy Prod
