$schema: https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
agents:
  queue: <%- prodBuildkiteQueueName %>

configs:
  plugins:
    - &aws-sm
      seek-oss/aws-sm#v2.3.2:
        env:
          NPM_READ_TOKEN: arn:aws:secretsmanager:ap-southeast-2:987872074697:secret:npm/npm-read-token

    - &docker-ecr-cache
      seek-oss/docker-ecr-cache#v2.2.0: &docker-ecr-cache-defaults
        cache-on:
          - .npmrc
          - package.json#.packageManager
          - pnpm-lock.yaml
        secrets: id=npm,src=tmp/.npmrc

    - &private-npm
      seek-oss/private-npm#v1.2.0:
        env: NPM_READ_TOKEN
        output-path: tmp/

  base-steps:
    - &deploy
      commands:
        - echo '--- pnpm install --offline'
        - pnpm install --offline
        - echo '+++ pnpm run deploy'
        - pnpm run deploy
      concurrency: 1
      plugins:
        - artifacts#v1.9.3:
            build: ${BUILDKITE_BUILD_ID}
            download: lib/*
        - *aws-sm
        - *private-npm
        - *docker-ecr-cache
        - docker-compose#v5.2.0:
            dependencies: false
            run: app
            propagate-environment: true
      retry:
        manual:
          # Only use this if you need to roll back a deployment ASAP.
          # Always follow up with a proper revert or fix in Git history.
          permit_on_passed: true

env:
  VERSION: ${BUILDKITE_COMMIT:0:7}.${BUILDKITE_BUILD_NUMBER}

steps:
  - label: 🧪 Test, Lint & Build
    artifact_paths: lib/**/*
    commands:
      - echo '--- pnpm install --offline'
      - pnpm install --offline
      - echo '+++ pnpm test:ci'
      - pnpm test:ci
      - echo '--- pnpm lint'
      - pnpm lint
      - echo '--- pnpm build'
      - pnpm build
    env:
      GET_GITHUB_TOKEN: please
    plugins:
      - *aws-sm
      - *private-npm
      - *docker-ecr-cache
      - docker-compose#v5.2.0:
          run: app
          environment:
            - GITHUB_API_TOKEN
          propagate-environment: true
    timeout_in_minutes: 10

  - agents:
      queue: <%- devBuildkiteQueueName %>
    branches: '!renovate-*'
    label: 🧖‍♀️ Warm Dev
    command: ':'
    plugins:
      - *aws-sm
      - *private-npm
      - seek-oss/docker-ecr-cache#v2.2.0:
          <<: *docker-ecr-cache-defaults
          skip-pull-from-cache: true

  - wait
  - block: 🙋🏻‍♀️ Deploy Dev
    branches: '!${BUILDKITE_PIPELINE_DEFAULT_BRANCH}'

  - <<: *deploy
    agents:
      queue: <%- devBuildkiteQueueName %>
    env:
      ENVIRONMENT: dev
    concurrency_group: <%- repoName %>/deploy/dev
    label: 🤞 Deploy Dev

  - wait

  - <<: *deploy
    env:
      ENVIRONMENT: prod
    branches: ${BUILDKITE_PIPELINE_DEFAULT_BRANCH}
    concurrency_group: <%- repoName %>/deploy/prod
    label: 🚀 Deploy Prod
