deployment: <%- devGantryEnvironmentName %>
env: development

minInstanceCount: 1
maxInstanceCount: 1

# Disable dashboard for cost savings
cloudwatchDashboardDisabled: true

openTelemetry:
  enabled: true
